from bot.loader import user_settings

# ==========================================
# 🇷🇺 RUSSIAN (RU)
# ==========================================
RU_TEXTS = {
    # ГЛАВНОЕ
    'menu': "🎧 <b>SOULYN MUSIC</b>\n<i>Your Soul. Your Sound.</i>\n\n⚡️ <b>Живой поиск</b>\nЖми кнопку ниже — музыка ищется мгновенно!\n\n💿 <b>Скачивание</b>\nНажми на трек — и он сразу твой.\n\n👇 <b>Меню:</b>",
    'welcome': "👋 <b>Привет, {}!</b>\n\nВыбери язык / Choose language:",
    'search_mode_text': "🔍 <b>Поиск</b>\n\nОтправь ссылку или используй Живой поиск.",
    'dl': "🚀 <b>Загружаю...</b>",
    'err': "❌ <b>Ошибка загрузки.</b>",
    '404': "😔 <b>Ничего не найдено.</b>",
    'limit_reached': "⚠️ <b>Лимит исчерпан.</b>\nДля безлимита нужно зарегистрироваться или получить Premium.",
    
    # КНОПКИ ГЛАВНЫЕ
    'btn_search_live': "🔎 Живой поиск",
    'btn_links_media': "🔗 Ссылки и Медиа",
    'btn_playlists': "📂 Плейлисты",
    'btn_profile': "👤 Профиль",
    'btn_settings': "⚙️ Настройки",
    'btn_support': "🆘 Поддержка",
    'btn_to_menu': "🏠 В меню",
    'btn_back': "🔙 Назад",
    'btn_close': "❌ Закрыть",
    'btn_fav_icon': "❤️ Избранное",
    'btn_reg': "✨ Регистрация",
    'btn_lang': "🌍 Язык / Language",
    'btn_channel': "📢 Канал",
    'btn_del_acc': "🗑 Удалить аккаунт",
    
    # НОВЫЕ КНОПКИ
    'btn_top_chart': "🔥 Топ Чарт",
    'btn_history': "📜 История",
    'btn_search_more': "🔎 Искать еще",
    'btn_cancel_search': "❌ Отмена",
    'top_chart_title': "🔥 <b>Топ {count} популярных треков</b>\n<i>Чаще всего скачивают:</i>",
    'top_chart_empty': "📭 Чарт пока пуст.",
    'history_title': "📜 <b>Твои последние запросы:</b>",
    'history_empty': "📭 История пуста.",
    'history_item': "▫️ <code>{}</code>",
    
    'help_media': "🔗 <b>Поиск по ссылкам и медиа</b>\n\n🔹 <b>Ссылки:</b> Отправь ссылку (YouTube, Spotify).\n🔹 <b>Shazam:</b> Отправь кружок, видео или аудио — я найду трек.",

    # ПЛЕЙЛИСТЫ
    'playlists': "📂 <b>Выбери плейлист:</b>",
    'playlists_list': "<b>📂 Твои плейлисты</b>",
    'playlist_view': "📂 <b>{}</b>",
    'playlist_empty': "📭 <b>{}</b>\nЗдесь пусто.",
    'pl_create': "➕ Создать",
    'pl_ask_name': "<b>Название плейлиста:</b>",
    'pl_created': "✅ Плейлист <b>{}</b> создан.",
    'pl_exists': "⚠️ Уже есть.",
    'btn_pl_add_track': "➕ Трек",
    'btn_pl_opts': "⚙️ Опции",
    'btn_rename_pl': "✏️ Имя",
    'btn_icon_pl': "🎨 Иконка",
    'btn_delete_pl': "🗑 Удалить",
    'add_track_title': "<b>Добавить в {}</b>",
    'select_from_fav': "Выбери трек:",
    'search_tip_pl': "Найди трек через поиск и нажми ➕ В плейлист — потом выбери <b>{}</b>.",
    'added_to_pl': "✅ Добавлено в <b>{}</b>",
    'add_to_pl': "➕ В плейлист",
    
    # ТРЕК
    'btn_lyrics_short': "📜 Текст",
    'searching_lyrics': "🔍 <b>Ищу текст...</b>",
    'added_to_fav_msg': "❤️ Добавлено",
    'removed_from_fav_msg': "💔 Удалено",
    'btn_remove_track': "🗑",
    'btn_move_track': "➡️",
    'track_removed': "🗑 Удалено.",
    'track_moved': "✅ Перемещено.",
    'select_move_target': "Куда?",
    
    # ПРОФИЛЬ
    'profile': "👤 <b>{}</b>\n\n🎧 Треков: <b>{}</b>",
    'settings': "<b>⚙️ Настройки</b>",
    'fav_title': "❤️ Избранное",
    'pl_opts_title': "⚙️ <b>Опции: {}</b>",
    
    # ПОДДЕРЖКА
    'ticket_ask': "✍️ Опиши проблему.",
    'btn_cancel_ticket': "Отмена",
    'ticket_sent': "✅ Отправлено.",
    'ticket_reply': "📩 <b>Ответ:</b>\n\n{}",
    
    # РЕГИСТРАЦИЯ
    'ask_nick': "Твое имя?",
    'ask_genres': "Жанры:",
    'btn_confirm': "Готово",
    'reg_success': "✅ <b>Готово!</b>",
    'guest_warning': "Без статистики. Ок?",
    'btn_go_reg': "Регистрация",
    'btn_sure_guest': "Я только посмотреть",
    'btn_guest': "Продолжить как гость",
    'del_confirm': "⚠️ Удалить аккаунт?",
    'del_success': "Удалено.",
    'btn_restore': "Восстановить",
    'restored': "✅ Готово!",
    
    # ЗАГЛУШКИ
    'pl_renamed': "✏️ Переименовано.",
    'pl_deleted': "🗑 Удалено.",
    'pl_del_confirm': "Удалить <b>{}</b>?",
    'pl_enter_new_name': "Новое имя:",
    'pl_select_icon': "Иконка:",
    'btn_yes_del': "Да",
    'btn_from_fav': "Из Избранного",
    'btn_search_new': "Поиск",
    'btn_back_to_pl': "« Назад",
    'select_playlist': "Куда?",
}

# ==========================================
# 🇬🇧 ENGLISH (EN)
# ==========================================
EN_TEXTS = {
    'menu': "🎧 <b>SOULYN MUSIC</b>\n<i>Your Soul. Your Sound.</i>\n\n⚡️ <b>Live Search</b>\nTap button below for instant results!\n\n💿 <b>Download</b>\nJust tap the track.\n\n👇 <b>Menu:</b>",
    'welcome': "👋 <b>Hello, {}!</b>\n\nChoose language:",
    'search_mode_text': "🔍 <b>Search</b>\n\nSend a link or use Live Search.",
    'dl': "🚀 <b>Downloading...</b>",
    'err': "❌ <b>Error.</b>",
    '404': "😔 <b>Not found.</b>",
    'limit_reached': "⚠️ <b>Limit reached.</b>\nRegister or get Premium for unlimited access.",
    
    'btn_search_live': "🔎 Live Search",
    'btn_links_media': "🔗 Links & Media",
    'btn_playlists': "📂 Playlists",
    'btn_profile': "👤 Profile",
    'btn_settings': "⚙️ Settings",
    'btn_support': "🆘 Support",
    'btn_to_menu': "🏠 Menu",
    'btn_back': "🔙 Back",
    'btn_close': "❌ Close",
    'btn_fav_icon': "❤️ Favorites",
    'btn_reg': "✨ Register",
    'btn_lang': "🌍 Language",
    'btn_channel': "📢 Channel",
    'btn_del_acc': "🗑 Delete Account",
    
    'btn_top_chart': "🔥 Top Chart",
    'btn_history': "📜 History",
    'btn_search_more': "🔎 Search more",
    'btn_cancel_search': "❌ Cancel",
    'top_chart_title': "🔥 <b>Top {count} Tracks</b>\n<i>Most downloaded:</i>",
    'top_chart_empty': "📭 Chart is empty.",
    'history_title': "📜 <b>Recent searches:</b>",
    'history_empty': "📭 History is empty.",
    'history_item': "▫️ <code>{}</code>",
    
    'help_media': "🔗 <b>Links & Media Search</b>\n\n🔹 <b>Links:</b> Send a link (YouTube, Spotify).\n🔹 <b>Shazam:</b> Send a voice note, video, or audio file.",

    'playlists': "📂 <b>Select playlist:</b>",
    'playlists_list': "<b>📂 Your Playlists</b>",
    'playlist_view': "📂 <b>{}</b>",
    'playlist_empty': "📭 <b>{}</b>\nIt's empty here.",
    'pl_create': "➕ Create",
    'pl_ask_name': "<b>Playlist name:</b>",
    'pl_created': "✅ Playlist <b>{}</b> created.",
    'pl_exists': "⚠️ Already exists.",
    'btn_pl_add_track': "➕ Track",
    'btn_pl_opts': "⚙️ Options",
    'btn_rename_pl': "✏️ Name",
    'btn_icon_pl': "🎨 Icon",
    'btn_delete_pl': "🗑 Delete",
    'add_track_title': "<b>Add to {}</b>",
    'select_from_fav': "Select track:",
    'search_tip_pl': "Find a track via search, tap ➕ To playlist, then select <b>{}</b>.",
    'added_to_pl': "✅ Added to <b>{}</b>",
    'add_to_pl': "➕ To playlist",
    
    'btn_lyrics_short': "📜 Lyrics",
    'searching_lyrics': "🔍 <b>Searching lyrics...</b>",
    'added_to_fav_msg': "❤️ Added",
    'removed_from_fav_msg': "💔 Removed",
    'btn_remove_track': "🗑",
    'btn_move_track': "➡️",
    'track_removed': "🗑 Removed.",
    'track_moved': "✅ Moved.",
    'select_move_target': "Where?",
    
    'profile': "👤 <b>{}</b>\n\n🎧 Tracks: <b>{}</b>",
    'settings': "<b>⚙️ Settings</b>",
    'fav_title': "❤️ Favorites",
    'pl_opts_title': "⚙️ <b>Options: {}</b>",
    
    'ticket_ask': "✍️ Describe your issue.",
    'btn_cancel_ticket': "Cancel",
    'ticket_sent': "✅ Sent.",
    'ticket_reply': "📩 <b>Reply:</b>\n\n{}",
    
    'ask_nick': "Your name?",
    'ask_genres': "Genres:",
    'btn_confirm': "Done",
    'reg_success': "✅ <b>Done!</b>",
    'guest_warning': "No stats. OK?",
    'btn_go_reg': "Register",
    'btn_sure_guest': "Just looking",
    'btn_guest': "Continue as guest",
    'del_confirm': "⚠️ Delete account?",
    'del_success': "Deleted.",
    'btn_restore': "Restore",
    'restored': "✅ Done!",
    
    'pl_renamed': "✏️ Renamed.",
    'pl_deleted': "🗑 Deleted.",
    'pl_del_confirm': "Delete <b>{}</b>?",
    'pl_enter_new_name': "New name:",
    'pl_select_icon': "Icon:",
    'btn_yes_del': "Yes",
    'btn_from_fav': "From Favorites",
    'btn_search_new': "Search",
    'btn_back_to_pl': "« Back",
    'select_playlist': "Where?",
}

# ==========================================
# 🇺🇦 UKRAINIAN (UA)
# ==========================================
UA_TEXTS = {
    'menu': "🎧 <b>SOULYN MUSIC</b>\n<i>Your Soul. Your Sound.</i>\n\n⚡️ <b>Живий пошук</b>\nТисни кнопку нижче — музика шукається миттєво!\n\n💿 <b>Завантаження</b>\nНатисни на трек — і він одразу твій.\n\n👇 <b>Меню:</b>",
    'welcome': "👋 <b>Привіт, {}!</b>\n\nОбери мову / Choose language:",
    'search_mode_text': "🔍 <b>Пошук</b>\n\nНадішли посилання або використовуй Живий пошук.",
    'dl': "🚀 <b>Завантажую...</b>",
    'err': "❌ <b>Помилка завантаження.</b>",
    '404': "😔 <b>Нічого не знайдено.</b>",
    'limit_reached': "⚠️ <b>Ліміт вичерпано.</b>\nДля безліміту потрібно зареєструватися або отримати Premium.",
    
    'btn_search_live': "🔎 Живий пошук",
    'btn_links_media': "🔗 Посилання та Медіа",
    'btn_playlists': "📂 Плейлисти",
    'btn_profile': "👤 Профіль",
    'btn_settings': "⚙️ Налаштування",
    'btn_support': "🆘 Підтримка",
    'btn_to_menu': "🏠 В меню",
    'btn_back': "🔙 Назад",
    'btn_close': "❌ Закрити",
    'btn_fav_icon': "❤️ Обране",
    'btn_reg': "✨ Реєстрація",
    'btn_lang': "🌍 Мова / Language",
    'btn_channel': "📢 Канал",
    'btn_del_acc': "🗑 Видалити акаунт",
    
    'btn_top_chart': "🔥 Топ Чарт",
    'btn_history': "📜 Історія",
    'btn_search_more': "🔎 Шукати ще",
    'btn_cancel_search': "❌ Скасувати",
    'top_chart_title': "🔥 <b>Топ {count} популярних треків</b>\n<i>Найчастіше завантажують:</i>",
    'top_chart_empty': "📭 Чарт поки порожній.",
    'history_title': "📜 <b>Твої останні запити:</b>",
    'history_empty': "📭 Історія порожня.",
    'history_item': "▫️ <code>{}</code>",
    
    'help_media': "🔗 <b>Пошук за посиланнями та медіа</b>\n\n🔹 <b>Посилання:</b> Надішли лінк (YouTube, Spotify).\n🔹 <b>Shazam:</b> Надішли кружечок, відео або аудіо — я знайду трек.",

    'playlists': "📂 <b>Обери плейлист:</b>",
    'playlists_list': "<b>📂 Твої плейлисти</b>",
    'playlist_view': "📂 <b>{}</b>",
    'playlist_empty': "📭 <b>{}</b>\nТут порожньо.",
    'pl_create': "➕ Створити",
    'pl_ask_name': "<b>Назва плейлиста:</b>",
    'pl_created': "✅ Плейлист <b>{}</b> створено.",
    'pl_exists': "⚠️ Вже є.",
    'btn_pl_add_track': "➕ Трек",
    'btn_pl_opts': "⚙️ Опції",
    'btn_rename_pl': "✏️ Ім'я",
    'btn_icon_pl': "🎨 Іконка",
    'btn_delete_pl': "🗑 Видалити",
    'add_track_title': "<b>Додати в {}</b>",
    'select_from_fav': "Обери трек:",
    'search_tip_pl': "Знайди трек через пошук і додай в <b>{}</b>.",
    'added_to_pl': "✅ Додано в <b>{}</b>",
    'add_to_pl': "➕ В плейлист",
    
    'btn_lyrics_short': "📜 Текст",
    'searching_lyrics': "🔍 <b>Шукаю текст...</b>",
    'added_to_fav_msg': "❤️ Додано",
    'removed_from_fav_msg': "💔 Видалено",
    'btn_remove_track': "🗑",
    'btn_move_track': "➡️",
    'track_removed': "🗑 Видалено.",
    'track_moved': "✅ Переміщено.",
    'select_move_target': "Куди?",
    
    'profile': "👤 <b>{}</b>\n\n🎧 Треків: <b>{}</b>",
    'settings': "<b>⚙️ Налаштування</b>",
    'fav_title': "❤️ Обране",
    'pl_opts_title': "⚙️ <b>Опції: {}</b>",
    
    'ticket_ask': "✍️ Опиши проблему.",
    'btn_cancel_ticket': "Скасувати",
    'ticket_sent': "✅ Надіслано.",
    'ticket_reply': "📩 <b>Відповідь:</b>\n\n{}",
    
    'ask_nick': "Твоє ім'я?",
    'ask_genres': "Жанри:",
    'btn_confirm': "Готово",
    'reg_success': "✅ <b>Готово!</b>",
    'guest_warning': "Без статистики. Ок?",
    'btn_go_reg': "Реєстрація",
    'btn_sure_guest': "Я тільки подивитись",
    'btn_guest': "Продовжити як гість",
    'del_confirm': "⚠️ Видалити акаунт?",
    'del_success': "Видалено.",
    'btn_restore': "Відновити",
    'restored': "✅ Готово!",
    
    'pl_renamed': "✏️ Перейменовано.",
    'pl_deleted': "🗑 Видалено.",
    'pl_del_confirm': "Видалити <b>{}</b>?",
    'pl_enter_new_name': "Нове ім'я:",
    'pl_select_icon': "Іконка:",
    'btn_yes_del': "Так",
    'btn_from_fav': "З Обраного",
    'btn_search_new': "Пошук",
    'btn_back_to_pl': "« Назад",
    'select_playlist': "Куди?",
}

# ==========================================
# 🇰🇿 KAZAKH (KZ)
# ==========================================
KZ_TEXTS = {
    'menu': "🎧 <b>SOULYN MUSIC</b>\n<i>Your Soul. Your Sound.</i>\n\n⚡️ <b>Жылдам іздеу</b>\nТөмендегі түймені бас — музыка лезде табылады!\n\n💿 <b>Жүктеу</b>\nТректі бас — ол бірден сенде.\n\n👇 <b>Мәзір:</b>",
    'welcome': "👋 <b>Сәлем, {}!</b>\n\nТілді таңдаңыз / Choose language:",
    'search_mode_text': "🔍 <b>Іздеу</b>\n\nСілтемені жібер немесе Жылдам іздеуді қолдан.",
    'dl': "🚀 <b>Жүктелуде...</b>",
    'err': "❌ <b>Жүктеу қатесі.</b>",
    '404': "😔 <b>Ештеңе табылмады.</b>",
    'limit_reached': "⚠️ <b>Лимит таусылды.</b>\nШексіз жүктеу үшін тіркелу немесе Premium алу қажет.",
    
    'btn_search_live': "🔎 Жылдам іздеу",
    'btn_links_media': "🔗 Сілтемелер",
    'btn_playlists': "📂 Плейлисттер",
    'btn_profile': "👤 Профиль",
    'btn_settings': "⚙️ Баптаулар",
    'btn_support': "🆘 Қолдау",
    'btn_to_menu': "🏠 Мәзірге",
    'btn_back': "🔙 Артқа",
    'btn_close': "❌ Жабу",
    'btn_fav_icon': "❤️ Таңдаулы",
    'btn_reg': "✨ Тіркелу",
    'btn_lang': "🌍 Тіл / Language",
    'btn_channel': "📢 Арна",
    'btn_del_acc': "🗑 Аккаунтты өшіру",
    
    'btn_top_chart': "🔥 Топ Чарт",
    'btn_history': "📜 Тарих",
    'btn_search_more': "🔎 Тағы іздеу",
    'btn_cancel_search': "❌ Болдырмау",
    'top_chart_title': "🔥 <b>Топ {count} танымал тректер</b>\n<i>Жиі жүктелетіндер:</i>",
    'top_chart_empty': "📭 Чарт әзірге бос.",
    'history_title': "📜 <b>Соңғы сұраныстар:</b>",
    'history_empty': "📭 Тарих бос.",
    'history_item': "▫️ <code>{}</code>",
    
    'help_media': "🔗 <b>Сілтемелер мен медиа арқылы іздеу</b>\n\n🔹 <b>Сілтемелер:</b> Сілтемені жібер (YouTube, Spotify).\n🔹 <b>Shazam:</b> Видео немесе аудио жібер — мен табамын.",

    'playlists': "📂 <b>Плейлистті таңда:</b>",
    'playlists_list': "<b>📂 Сенің плейлисттерің</b>",
    'playlist_view': "📂 <b>{}</b>",
    'playlist_empty': "📭 <b>{}</b>\nБұл жер бос.",
    'pl_create': "➕ Жасау",
    'pl_ask_name': "<b>Плейлист аты:</b>",
    'pl_created': "✅ Плейлист <b>{}</b> жасалды.",
    'pl_exists': "⚠️ Бар.",
    'btn_pl_add_track': "➕ Трек",
    'btn_pl_opts': "⚙️ Опциялар",
    'btn_rename_pl': "✏️ Аты",
    'btn_icon_pl': "🎨 Белгіше",
    'btn_delete_pl': "🗑 Өшіру",
    'add_track_title': "<b>{} ішіне қосу</b>",
    'select_from_fav': "Тректі таңда:",
    'search_tip_pl': "Тректі тауып, <b>{}</b> ішіне қос.",
    'added_to_pl': "✅ <b>{}</b> ішіне қосылды",
    'add_to_pl': "➕ Плейлистке",
    
    'btn_lyrics_short': "📜 Мәтін",
    'searching_lyrics': "🔍 <b>Мәтін ізделуде...</b>",
    'added_to_fav_msg': "❤️ Қосылды",
    'removed_from_fav_msg': "💔 Өшірілді",
    'btn_remove_track': "🗑",
    'btn_move_track': "➡️",
    'track_removed': "🗑 Өшірілді.",
    'track_moved': "✅ Жылжытылды.",
    'select_move_target': "Қайда?",
    
    'profile': "👤 <b>{}</b>\n\n🎧 Тректер: <b>{}</b>",
    'settings': "<b>⚙️ Баптаулар</b>",
    'fav_title': "❤️ Таңдаулы",
    'pl_opts_title': "⚙️ <b>Опциялар: {}</b>",
    
    'ticket_ask': "✍️ Мәселені сипатта.",
    'btn_cancel_ticket': "Болдырмау",
    'ticket_sent': "✅ Жіберілді.",
    'ticket_reply': "📩 <b>Жауап:</b>\n\n{}",
    
    'ask_nick': "Есімің?",
    'ask_genres': "Жанрлар:",
    'btn_confirm': "Дайын",
    'reg_success': "✅ <b>Дайын!</b>",
    'guest_warning': "Статистикасыз. Жарай ма?",
    'btn_go_reg': "Тіркелу",
    'btn_sure_guest': "Жәй қарап көрем",
    'btn_guest': "Қонақ ретінде жалғастыру",
    'del_confirm': "⚠️ Аккаунтты өшіру?",
    'del_success': "Өшірілді.",
    'btn_restore': "Қалпына келтіру",
    'restored': "✅ Дайын!",
    
    'pl_renamed': "✏️ Аты өзгертілді.",
    'pl_deleted': "🗑 Өшірілді.",
    'pl_del_confirm': "<b>{}</b> өшіру?",
    'pl_enter_new_name': "Жаңа атау:",
    'pl_select_icon': "Белгіше:",
    'btn_yes_del': "Иә",
    'btn_from_fav': "Таңдаулыдан",
    'btn_search_new': "Іздеу",
    'btn_back_to_pl': "« Артқа",
    'select_playlist': "Қайда?",
}

# ==========================================
# 🇺🇿 UZBEK (UZ)
# ==========================================
UZ_TEXTS = {
    'menu': "🎧 <b>SOULYN MUSIC</b>\n<i>Your Soul. Your Sound.</i>\n\n⚡️ <b>Jonli qidiruv</b>\nQuyidagi tugmani bosing — musiqa tez topiladi!\n\n💿 <b>Yuklab olish</b>\nTreklarni bosing — va ular darhol sizda.\n\n👇 <b>Menyu:</b>",
    'welcome': "👋 <b>Salom, {}!</b>\n\nTilni tanlang / Choose language:",
    'search_mode_text': "🔍 <b>Qidiruv</b>\n\nHavola yuboring yoki Jonli qidiruvdan foydalaning.",
    'dl': "🚀 <b>Yuklanmoqda...</b>",
    'err': "❌ <b>Yuklashda xatolik.</b>",
    '404': "😔 <b>Hech narsa topilmadi.</b>",
    'limit_reached': "⚠️ <b>Limit tugadi.</b>\nCheksiz yuklash uchun ro'yxatdan o'ting yoki Premium oling.",
    
    'btn_search_live': "🔎 Jonli qidiruv",
    'btn_links_media': "🔗 Havolalar",
    'btn_playlists': "📂 Pleylistlar",
    'btn_profile': "👤 Profil",
    'btn_settings': "⚙️ Sozlamalar",
    'btn_support': "🆘 Yordam",
    'btn_to_menu': "🏠 Menyuga",
    'btn_back': "🔙 Orqaga",
    'btn_close': "❌ Yopish",
    'btn_fav_icon': "❤️ Sevimlilar",
    'btn_reg': "✨ Ro'yxatdan o'tish",
    'btn_lang': "🌍 Til / Language",
    'btn_channel': "📢 Kanal",
    'btn_del_acc': "🗑 Hisobni o'chirish",
    
    'btn_top_chart': "🔥 Top Chart",
    'btn_history': "📜 Tarix",
    'btn_search_more': "🔎 Yana qidirish",
    'btn_cancel_search': "❌ Bekor qilish",
    'top_chart_title': "🔥 <b>Top {count} mashhur treklar</b>\n<i>Eng ko'p yuklangan:</i>",
    'top_chart_empty': "📭 Chart hozircha bo'sh.",
    'history_title': "📜 <b>So'nggi so'rovlar:</b>",
    'history_empty': "📭 Tarix bo'sh.",
    'history_item': "▫️ <code>{}</code>",
    
    'help_media': "🔗 <b>Havolalar va media orqali qidiruv</b>\n\n🔹 <b>Havolalar:</b> Havola yuboring (YouTube, Spotify).\n🔹 <b>Shazam:</b> Video yoki audio yuboring — men topaman.",

    'playlists': "📂 <b>Pleylistni tanlang:</b>",
    'playlists_list': "<b>📂 Sizning pleylistlaringiz</b>",
    'playlist_view': "📂 <b>{}</b>",
    'playlist_empty': "📭 <b>{}</b>\nBu yer bo'sh.",
    'pl_create': "➕ Yaratish",
    'pl_ask_name': "<b>Pleylist nomi:</b>",
    'pl_created': "✅ Pleylist <b>{}</b> yaratildi.",
    'pl_exists': "⚠️ Mavjud.",
    'btn_pl_add_track': "➕ Trek",
    'btn_pl_opts': "⚙️ Opsiyalar",
    'btn_rename_pl': "✏️ Nom",
    'btn_icon_pl': "🎨 Belgi",
    'btn_delete_pl': "🗑 O'chirish",
    'add_track_title': "<b>{} ga qo'shish</b>",
    'select_from_fav': "Trekni tanlang:",
    'search_tip_pl': "Trekni toping va <b>{}</b> ga qo'shing.",
    'added_to_pl': "✅ <b>{}</b> ga qo'shildi",
    'add_to_pl': "➕ Pleylistga",
    
    'btn_lyrics_short': "📜 Matn",
    'searching_lyrics': "🔍 <b>Matn qidirilmoqda...</b>",
    'added_to_fav_msg': "❤️ Qo'shildi",
    'removed_from_fav_msg': "💔 O'chirildi",
    'btn_remove_track': "🗑",
    'btn_move_track': "➡️",
    'track_removed': "🗑 O'chirildi.",
    'track_moved': "✅ Ko'chirildi.",
    'select_move_target': "Qayerga?",
    
    'profile': "👤 <b>{}</b>\n\n🎧 Treklar: <b>{}</b>",
    'settings': "<b>⚙️ Sozlamalar</b>",
    'fav_title': "❤️ Sevimlilar",
    'pl_opts_title': "⚙️ <b>Opsiyalar: {}</b>",
    
    'ticket_ask': "✍️ Muammoni tasvirlang.",
    'btn_cancel_ticket': "Bekor qilish",
    'ticket_sent': "✅ Yuborildi.",
    'ticket_reply': "📩 <b>Javob:</b>\n\n{}",
    
    'ask_nick': "Ismingiz?",
    'ask_genres': "Janrlar:",
    'btn_confirm': "Tayyor",
    'reg_success': "✅ <b>Tayyor!</b>",
    'guest_warning': "Statistikasiz. Rozimisiz?",
    'btn_go_reg': "Ro'yxatdan o'tish",
    'btn_sure_guest': "Shunchaki ko'raman",
    'btn_guest': "Mehmon sifatida davom etish",
    'del_confirm': "⚠️ Hisobni o'chirasizmi?",
    'del_success': "O'chirildi.",
    'btn_restore': "Tiklash",
    'restored': "✅ Tayyor!",
    
    'pl_renamed': "✏️ Qayta nomlandi.",
    'pl_deleted': "🗑 O'chirildi.",
    'pl_del_confirm': "<b>{}</b> o'chirilsinmi?",
    'pl_enter_new_name': "Yangi nom:",
    'pl_select_icon': "Belgi:",
    'btn_yes_del': "Ha",
    'btn_from_fav': "Sevimlilardan",
    'btn_search_new': "Qidiruv",
    'btn_back_to_pl': "« Orqaga",
    'select_playlist': "Qayerga?",
}

# ==========================================
# 🇦🇪 ARABIC (AR)
# ==========================================
AR_TEXTS = {
    'menu': "🎧 <b>SOULYN MUSIC</b>\n<i>Your Soul. Your Sound.</i>\n\n⚡️ <b>البحث المباشر</b>\nاضغط على الزر أدناه - الموسيقى تأتي فوراً!\n\n💿 <b>تحميل</b>\nاضغط على الأغنية - وستصبح لك.\n\n👇 <b>القائمة:</b>",
    'welcome': "👋 <b>أهلاً بك، {}!</b>\n\nاختر اللغة / Choose language:",
    'search_mode_text': "🔍 <b>بحث</b>\n\nأرسل رابطاً أو استخدم البحث المباشر.",
    'dl': "🚀 <b>جاري التحميل...</b>",
    'err': "❌ <b>خطأ في التحميل.</b>",
    '404': "😔 <b>لم يتم العثور على شيء.</b>",
    'limit_reached': "⚠️ <b>تم الوصول للحد الأقصى.</b>\nلتحميل بلا حدود، يجب التسجيل أو الحصول على Premium.",
    
    'btn_search_live': "🔎 بحث مباشر",
    'btn_links_media': "🔗 روابط ووسائط",
    'btn_playlists': "📂 قوائم التشغيل",
    'btn_profile': "👤 الملف الشخصي",
    'btn_settings': "⚙️ الإعدادات",
    'btn_support': "🆘 الدعم",
    'btn_to_menu': "🏠 القائمة",
    'btn_back': "🔙 رجوع",
    'btn_close': "❌ إغلاق",
    'btn_fav_icon': "❤️ المفضلة",
    'btn_reg': "✨ تسجيل",
    'btn_lang': "🌍 اللغة / Language",
    'btn_channel': "📢 القناة",
    'btn_del_acc': "🗑 حذف الحساب",
    
    'btn_top_chart': "🔥 أفضل الأغاني",
    'btn_history': "📜 السجل",
    'btn_search_more': "🔎 بحث المزيد",
    'btn_cancel_search': "❌ إلغاء",
    'top_chart_title': "🔥 <b>أفضل {count} أغنية</b>\n<i>الأكثر تحميلاً:</i>",
    'top_chart_empty': "📭 القائمة فارغة حالياً.",
    'history_title': "📜 <b>عمليات البحث الأخيرة:</b>",
    'history_empty': "📭 السجل فارغ.",
    'history_item': "▫️ <code>{}</code>",
    
    'help_media': "🔗 <b>البحث بالروابط والوسائط</b>\n\n🔹 <b>الروابط:</b> أرسل رابطاً (YouTube, Spotify).\n🔹 <b>Shazam:</b> أرسل رسالة صوتية أو فيديو.",

    'playlists': "📂 <b>اختر قائمة التشغيل:</b>",
    'playlists_list': "<b>📂 قوائم التشغيل الخاصة بك</b>",
    'playlist_view': "📂 <b>{}</b>",
    'playlist_empty': "📭 <b>{}</b>\nفارغ هنا.",
    'pl_create': "➕ إنشاء",
    'pl_ask_name': "<b>اسم القائمة:</b>",
    'pl_created': "✅ تم إنشاء القائمة <b>{}</b>.",
    'pl_exists': "⚠️ موجودة بالفعل.",
    'btn_pl_add_track': "➕ أغنية",
    'btn_pl_opts': "⚙️ خيارات",
    'btn_rename_pl': "✏️ الاسم",
    'btn_icon_pl': "🎨 أيقونة",
    'btn_delete_pl': "🗑 حذف",
    'add_track_title': "<b>إضافة إلى {}</b>",
    'select_from_fav': "اختر أغنية:",
    'search_tip_pl': "ابحث عن أغنية وأضفها إلى <b>{}</b>.",
    'added_to_pl': "✅ تمت الإضافة إلى <b>{}</b>",
    'add_to_pl': "➕ إلى القائمة",
    
    'btn_lyrics_short': "📜 كلمات",
    'searching_lyrics': "🔍 <b>جاري البحث عن الكلمات...</b>",
    'added_to_fav_msg': "❤️ تمت الإضافة",
    'removed_from_fav_msg': "💔 تمت الإزالة",
    'btn_remove_track': "🗑",
    'btn_move_track': "➡️",
    'track_removed': "🗑 تم الحذف.",
    'track_moved': "✅ تم النقل.",
    'select_move_target': "إلى أين؟",
    
    'profile': "👤 <b>{}</b>\n\n🎧 الأغاني: <b>{}</b>",
    'settings': "<b>⚙️ الإعدادات</b>",
    'fav_title': "❤️ المفضلة",
    'pl_opts_title': "⚙️ <b>خيارات: {}</b>",
    
    'ticket_ask': "✍️ صف المشكلة.",
    'btn_cancel_ticket': "إلغاء",
    'ticket_sent': "✅ تم الإرسال.",
    'ticket_reply': "📩 <b>رد:</b>\n\n{}",
    
    'ask_nick': "اسمك؟",
    'ask_genres': "الأنواع:",
    'btn_confirm': "تم",
    'reg_success': "✅ <b>تم!</b>",
    'guest_warning': "بدون إحصائيات. موافق؟",
    'btn_go_reg': "تسجيل",
    'btn_sure_guest': "مشاهدة فقط",
    'btn_guest': "الاستمرار كضيف",
    'del_confirm': "⚠️ حذف الحساب؟",
    'del_success': "تم الحذف.",
    'btn_restore': "استعادة",
    'restored': "✅ تم!",
    
    'pl_renamed': "✏️ تم تغيير الاسم.",
    'pl_deleted': "🗑 تم الحذف.",
    'pl_del_confirm': "حذف <b>{}</b>؟",
    'pl_enter_new_name': "الاسم الجديد:",
    'pl_select_icon': "الأيقونة:",
    'btn_yes_del': "نعم",
    'btn_from_fav': "من المفضلة",
    'btn_search_new': "بحث",
    'btn_back_to_pl': "« رجوع",
    'select_playlist': "إلى أين؟",
}

# ==========================================
# 🔧 LOGIC
# ==========================================

LANGUAGES = {
    'ru': RU_TEXTS,
    'en': EN_TEXTS,
    'ua': UA_TEXTS,
    'kz': KZ_TEXTS,
    'uz': UZ_TEXTS,
    'ar': AR_TEXTS
}

def T(uid, key, default=None):
    """Получить перевод. Берёт язык из RAM кэша user_settings."""
    lang_code = user_settings.get(uid, {}).get("lang", "ru")
    selected_dict = LANGUAGES.get(lang_code, RU_TEXTS)
    
    if default is not None:
        return selected_dict.get(key, default)
    
    return selected_dict.get(key, RU_TEXTS.get(key, f"key:{key}"))